import { Box, Typography, Container, Paper, Divider } from "@mui/material";
import { Link } from "react-router-dom";
import usePageMeta from "../hooks/usePageMeta";

const C = { brand: "#0B5E55", surface: "#F7F9F8", border: "rgba(11,94,85,0.12)", text: "#0F2420", muted: "#4A6B67", faint: "#8AADAA" };

const Section = ({ title, children }) => (
  <Box sx={{ mb: 4 }}>
    <Typography component="h2" sx={{ fontSize: 16, fontWeight: 800, color: C.brand, mb: 1.5 }}>{title}</Typography>
    <Box>{children}</Box>
  </Box>
);
const P = ({ children }) => <Typography sx={{ fontSize: 14, color: C.muted, lineHeight: 1.85, mb: 1.5 }}>{children}</Typography>;
const Li = ({ children }) => <Typography component="li" sx={{ fontSize: 14, color: C.muted, lineHeight: 1.85, mb: 0.5, ml: 2 }}>{children}</Typography>;

const CookieRow = ({ name, type, purpose, duration }) => (
  <Box sx={{ display: "grid", gridTemplateColumns: { xs: "1fr", sm: "1.5fr 1fr 3fr 1fr" }, gap: 1, py: 1.5, borderBottom: `1px solid ${C.border}`, "&:last-child": { borderBottom: "none" } }}>
    <Typography sx={{ fontSize: 13, fontWeight: 700, color: C.text }}>{name}</Typography>
    <Box sx={{ display: "inline-flex", alignSelf: "start", px: 1.2, py: 0.3, borderRadius: 99, bgcolor: type === "Essential" ? "#E6F5F3" : "#FFF3E0", border: `1px solid ${type === "Essential" ? "rgba(11,94,85,0.2)" : "rgba(230,81,0,0.2)"}` }}>
      <Typography sx={{ fontSize: 11, fontWeight: 700, color: type === "Essential" ? C.brand : "#E65100" }}>{type}</Typography>
    </Box>
    <Typography sx={{ fontSize: 13, color: C.muted }}>{purpose}</Typography>
    <Typography sx={{ fontSize: 12, color: C.faint }}>{duration}</Typography>
  </Box>
);

export default function LegalPageEN() {
  usePageMeta({
    title:       "Legal Notice & Cookie Policy — Nui App",
    description: "Legal notice and cookie policy for Nui: who operates the service, intellectual property, and how we use cookies.",
    canonical:   "/en/legal",
    alternates: [
      { hreflang: "es-AR",    href: "/legal" },
      { hreflang: "en",       href: "/en/legal" },
      { hreflang: "x-default", href: "/legal" },
    ],
  });
  const updated = "September 2026";

  return (
    <Box sx={{ background: C.surface, minHeight: "100vh", py: 6 }}>
      <Container maxWidth="md">

        <Box sx={{ mb: 5 }}>
          <Typography
            component={Link}
            to="/en"
            sx={{ fontSize: 13, color: C.brand, fontWeight: 700, textDecoration: "none", mb: 2, display: "inline-block", "&:hover": { textDecoration: "underline" } }}
          >
            ← Back to Nui
          </Typography>
          <Typography component="h1" sx={{ fontSize: 28, fontWeight: 900, color: C.text, letterSpacing: "-0.8px", mb: 1 }}>
            Legal Notice & Cookie Policy
          </Typography>
          <Typography sx={{ fontSize: 13, color: C.faint }}>Last updated: {updated}</Typography>
        </Box>

        <Box sx={{ mb: 3, p: 2.5, borderRadius: 3, bgcolor: "#FFF8E1", border: "1px solid rgba(245,166,35,0.3)" }}>
          <Typography sx={{ fontSize: 13, color: "#7B5800", fontWeight: 700, mb: 0.5 }}>
            📝 Draft notice
          </Typography>
          <Typography sx={{ fontSize: 13, color: "#5D4200", lineHeight: 1.7 }}>
            This page is a good-faith draft, written to reflect how Nui actually works today. It has not
            yet been reviewed by a licensed attorney. If you have questions about your specific legal
            rights, please consult independent counsel.
          </Typography>
        </Box>

        <Paper elevation={0} sx={{ borderRadius: 4, border: `1px solid ${C.border}`, p: { xs: 3, md: 5 }, mb: 4 }}>

          <Typography sx={{ fontSize: 20, fontWeight: 900, color: C.text, mb: 3, letterSpacing: "-0.4px" }}>
            Legal Notice
          </Typography>

          <Section title="1. Who operates this service">
            <Box sx={{ p: 2.5, borderRadius: 3, bgcolor: "#E6F5F3", border: `1px solid rgba(11,94,85,0.15)`, mb: 2 }}>
              <Typography sx={{ fontSize: 14, color: C.muted, lineHeight: 2 }}>
                <strong>Service name:</strong> Nui<br />
                <strong>Operated from:</strong> Argentina<br />
                <strong>Contact email:</strong> info@nuiapp.com
              </Typography>
            </Box>
          </Section>

          <Divider sx={{ mb: 4, borderColor: C.border }} />

          <Section title="2. What the service is">
            <P>
              <strong>Nui</strong> is a digital platform offering AI-powered nutrition analysis, recipes,
              and personalized training.
            </P>
            <P>
              Content generated by Nui is <strong>informational only</strong>. It is not medical, dietary,
              or professional health advice. Nui is not a regulated healthcare service.
            </P>
          </Section>

          <Divider sx={{ mb: 4, borderColor: C.border }} />

          <Section title="3. Intellectual property">
            <P>
              Nui's name, logos, interface design, source code, and analysis methodology are protected by
              applicable intellectual property law. Reproduction, in whole or in part, without express
              written authorization is prohibited.
            </P>
            <P>
              Content you upload (e.g. photos of product labels) remains yours. By uploading it, you grant
              Nui a limited, non-exclusive, royalty-free license to process it solely to generate the
              analysis you requested.
            </P>
          </Section>

          <Divider sx={{ mb: 4, borderColor: C.border }} />

          <Section title="4. Limitation of liability for AI results">
            <P>
              Nutrition analyses, training plans, and recipes generated by Nui come from AI models and may
              contain inaccuracies. They're based on the data you provide and on reference nutrition guidance.
            </P>
            <P>
              <strong>Nui is not responsible for health, diet, or fitness decisions made solely based on
              results from the platform.</strong> Always consult a certified nutritionist, physician, or trainer.
            </P>
          </Section>

          <Divider sx={{ mb: 4, borderColor: C.border }} />

          <Section title="5. Links to other sites">
            <P>
              Nui may link to third-party websites. We don't control their content and aren't responsible
              for their privacy practices or security.
            </P>
          </Section>

        </Paper>

        <Paper elevation={0} sx={{ borderRadius: 4, border: `1px solid ${C.border}`, p: { xs: 3, md: 5 } }}>

          <Typography sx={{ fontSize: 20, fontWeight: 900, color: C.text, mb: 3, letterSpacing: "-0.4px" }}>
            Cookie Policy
          </Typography>

          <Section title="What are cookies?">
            <P>
              Cookies are small text files stored on your device when you visit a website. They let a site
              remember your preferences, keep you signed in, and improve your experience.
            </P>
          </Section>

          <Divider sx={{ mb: 4, borderColor: C.border }} />

          <Section title="Cookies we use">
            <P>Nui uses two kinds of cookies/local storage:</P>

            <Box sx={{ display: { xs: "none", sm: "grid" }, gridTemplateColumns: "1.5fr 1fr 3fr 1fr", gap: 1, pb: 1, mb: 1, borderBottom: `2px solid ${C.border}` }}>
              {["Cookie", "Type", "Purpose", "Duration"].map(h => (
                <Typography key={h} sx={{ fontSize: 11, fontWeight: 700, color: C.faint, textTransform: "uppercase", letterSpacing: "0.06em" }}>{h}</Typography>
              ))}
            </Box>

            <CookieRow
              name="nutrismartToken"
              type="Essential"
              purpose="Stores your authentication token so you stay signed in."
              duration="7 days"
            />
            <CookieRow
              name="nutrismart_training_*"
              type="Essential"
              purpose="Locally saves your active training plans for offline access."
              duration="Session"
            />
            <CookieRow
              name="nutrismart_recipes_*"
              type="Essential"
              purpose="Stores recipe preferences and recent searches for Instant Recipes."
              duration="Session"
            />
            <CookieRow
              name="Google OAuth"
              type="Third party"
              purpose="Google's own authentication cookies, used only if you sign in with Google."
              duration="Set by Google"
            />
            <CookieRow
              name="_ga, _ga_*"
              type="Analytics"
              purpose="Google Analytics — anonymized usage statistics. Only set after you accept cookies in the banner."
              duration="Up to 2 years"
            />
          </Section>

          <Divider sx={{ mb: 4, borderColor: C.border }} />

          <Section title="Your choice">
            <P>
              When you first visit Nui, you'll see a cookie banner with <strong>Accept</strong> and{" "}
              <strong>Reject</strong> options. Essential cookies (the ones that make the app work — signing
              in, saving your plan) are always active, since the Service can't function without them.
              Analytics cookies (Google Analytics) are <strong>off by default</strong> and only turn on if
              you click Accept. You can change your choice at any time by clearing your browser's site data
              for nuiapp.com, which will show the banner again on your next visit.
            </P>
            <P>
              Nui does not use advertising, remarketing, or cross-site tracking cookies.
            </P>
          </Section>

          <Divider sx={{ mb: 4, borderColor: C.border }} />

          <Section title="Managing cookies in your browser">
            <Box component="ul" sx={{ pl: 1, mb: 2 }}>
              <Li><strong>Chrome:</strong> Settings → Privacy and security → Clear browsing data.</Li>
              <Li><strong>Firefox:</strong> Settings → Privacy & Security → Cookies and Site Data.</Li>
              <Li><strong>Safari:</strong> Preferences → Privacy → Manage Website Data.</Li>
              <Li><strong>Edge:</strong> Settings → Privacy, search, and services → Clear browsing data.</Li>
            </Box>
            <P>Note: clearing essential cookies will sign you out and remove locally saved training plans.</P>
          </Section>

          <Divider sx={{ mb: 4, borderColor: C.border }} />

          <Section title="Contact">
            <P>
              Questions about this Cookie Policy or the Legal Notice? Contact us at:{" "}
              <strong>info@nuiapp.com</strong>
            </P>
          </Section>

        </Paper>
      </Container>
    </Box>
  );
}
