import { Box, Typography, Container, Paper, Divider } from "@mui/material";
import { Link } from "react-router-dom";
import usePageMeta from "../hooks/usePageMeta";

const C = { brand: "#0B5E55", surface: "#F7F9F8", border: "rgba(11,94,85,0.12)", text: "#0F2420", muted: "#4A6B67", faint: "#8AADAA" };

const Section = ({ title, children }) => (
  <Box sx={{ mb: 4 }}>
    <Typography component="h2" sx={{ fontSize: 16, fontWeight: 800, color: C.brand, mb: 1.5 }}>{title}</Typography>
    <Box>{children}</Box>
  </Box>
);
const P = ({ children }) => <Typography sx={{ fontSize: 14, color: C.muted, lineHeight: 1.85, mb: 1.5 }}>{children}</Typography>;
const Li = ({ children }) => <Typography component="li" sx={{ fontSize: 14, color: C.muted, lineHeight: 1.85, mb: 0.5, ml: 2 }}>{children}</Typography>;

export default function TermsPageEN() {
  usePageMeta({
    title:       "Terms & Conditions — Nui App",
    description: "Terms and conditions for using Nui: sign-up, subscriptions, cancellations, and acceptable use.",
    canonical:   "/en/terms",
    alternates: [
      { hreflang: "es-AR",    href: "/terminos" },
      { hreflang: "en",       href: "/en/terms" },
      { hreflang: "x-default", href: "/terminos" },
    ],
  });
  const updated = "September 2026";

  return (
    <Box sx={{ background: C.surface, minHeight: "100vh", py: 6 }}>
      <Container maxWidth="md">

        <Box sx={{ mb: 5 }}>
          <Typography
            component={Link}
            to="/en"
            sx={{ fontSize: 13, color: C.brand, fontWeight: 700, textDecoration: "none", mb: 2, display: "inline-block", "&:hover": { textDecoration: "underline" } }}
          >
            ← Back to Nui
          </Typography>
          <Typography component="h1" sx={{ fontSize: 28, fontWeight: 900, color: C.text, letterSpacing: "-0.8px", mb: 1 }}>
            Terms & Conditions
          </Typography>
          <Typography sx={{ fontSize: 13, color: C.faint }}>Last updated: {updated}</Typography>
        </Box>

        <Box sx={{ mb: 3, p: 2.5, borderRadius: 3, bgcolor: "#FFF8E1", border: "1px solid rgba(245,166,35,0.3)" }}>
          <Typography sx={{ fontSize: 13, color: "#7B5800", fontWeight: 700, mb: 0.5 }}>
            📝 Draft notice
          </Typography>
          <Typography sx={{ fontSize: 13, color: "#5D4200", lineHeight: 1.7 }}>
            This page is a good-faith draft, written to reflect how Nui actually works today. It has not
            yet been reviewed by a licensed attorney. If you have questions about your specific legal
            rights, please consult independent counsel.
          </Typography>
        </Box>

        <Paper elevation={0} sx={{ borderRadius: 4, border: `1px solid ${C.border}`, p: { xs: 3, md: 5 } }}>

          <Section title="1. Acceptance of these terms">
            <P>
              By signing up for or using <strong>Nui</strong> (the "Service"), you agree to be bound by these
              Terms & Conditions and our Privacy Policy. If you don't agree, please don't use the Service.
            </P>
            <P>
              The Service is intended for people <strong>18 years or older</strong>, or minors with the
              supervision and consent of a parent or legal guardian.
            </P>
          </Section>

          <Divider sx={{ mb: 4, borderColor: C.border }} />

          <Section title="2. What the service does">
            <P>Nui is a digital platform that uses AI to offer:</P>
            <Box component="ul" sx={{ pl: 1, mb: 2 }}>
              <Li><strong>Food analysis:</strong> processing-level assessment (NOVA-style classification) and a 0–100 score based on product labels.</Li>
              <Li><strong>Instant Recipes:</strong> healthy recipe generation based on available ingredients.</Li>
              <Li><strong>Training:</strong> personalized exercise plans based on your profile.</Li>
            </Box>
            <P>
              Results generated by Nui are <strong>for informational purposes only</strong>. They are not
              a medical diagnosis, treatment, clinical nutrition advice, or a prescription of any kind.
              The Service is not a medical device and is not intended to diagnose, treat, cure, or prevent
              any illness or health condition. Always consult a licensed health professional before making
              decisions about your diet, fitness, or health.
            </P>
            <P>
              <strong>Physical activity carries risk.</strong> Before starting any training plan generated
              by Nui, consider the risks involved and consult a medical professional — this is especially
              important if you are pregnant, nursing, or have a heart condition, injury, disability, or any
              other medical condition. Start slowly, don't exceed your capabilities, and stop immediately if
              you feel dizzy, dehydrated, or unwell. You assume the risks associated with any physical
              activity you engage in through the Service.
            </P>
          </Section>

          <Divider sx={{ mb: 4, borderColor: C.border }} />

          <Section title="3. Your account">
            <P>
              To use the Service you need to sign up with an email and password, or with your Google account.
              You're responsible for keeping your credentials confidential and for all activity under your account.
            </P>
            <P>
              We may suspend or terminate accounts that violate these Terms, misuse the Service, or provide
              false information during sign-up.
            </P>
          </Section>

          <Divider sx={{ mb: 4, borderColor: C.border }} />

          <Section title="4. Plans and subscriptions">
            <P>Nui offers the following plans:</P>
            <Box component="ul" sx={{ pl: 1, mb: 2 }}>
              <Li><strong>Free plan:</strong> up to 3 trial food analyses, at no cost.</Li>
              <Li><strong>Silver plan:</strong> 1 food analysis per day, plus full access to Instant Recipes and Training. Billed monthly.</Li>
              <Li><strong>Gold plan:</strong> unlimited daily analyses, plus full access to all modules. Billed monthly.</Li>
            </Box>
            <P>
              Payments are processed securely by <strong>Stripe, Inc.</strong> Prices are shown in US dollars (USD)
              and may change; we'll give you advance notice of any price change.
            </P>
          </Section>

          <Divider sx={{ mb: 4, borderColor: C.border }} />

          <Section title="5. Cancellation and refunds">
            <P>
              You can cancel your subscription at any time from your account settings. Cancellation takes
              effect at the end of your current billing period — you keep access until then.
            </P>
            <P>
              We don't issue refunds for partial billing periods, except where required by law. If you're
              charged in error or charged twice, we'll refund the correct amount within 10 business days
              of your request.
            </P>
          </Section>

          <Divider sx={{ mb: 4, borderColor: C.border }} />

          <Section title="6. Acceptable use">
            <P>By using Nui, you agree not to:</P>
            <Box component="ul" sx={{ pl: 1, mb: 2 }}>
              <Li>Use the Service for any unlawful or unauthorized purpose.</Li>
              <Li>Attempt to access other users' data or systems without authorization.</Li>
              <Li>Reverse-engineer, decompile, or try to extract the platform's source code.</Li>
              <Li>Introduce viruses, malware, or malicious code of any kind.</Li>
              <Li>Intentionally overload the Service's infrastructure.</Li>
              <Li>Reproduce, distribute, or resell Service content without express authorization.</Li>
              <Li>Use data mining, scraping, bots, or similar methods to extract content or data from the Service.</Li>
              <Li>Use any content or data obtained from the Service to train, fine-tune, or benchmark machine learning or AI models, or any other technology, without our written consent.</Li>
            </Box>
          </Section>

          <Divider sx={{ mb: 4, borderColor: C.border }} />

          <Section title="7. Content you submit">
            <P>
              Some parts of the Service let you upload content — for example, photos of product labels for
              analysis. You keep ownership of what you upload. By uploading it, you grant Nui a limited,
              non-exclusive, worldwide license to process and store that content solely to provide you the
              Service (generate your analysis, save your history, etc.). This license ends when you delete
              the content or your account, except where we're required to retain it for a legitimate reason
              (e.g. legal compliance).
            </P>
            <P>
              You confirm that you have the rights necessary to upload the content you submit, and that it
              doesn't violate any third party's rights.
            </P>
          </Section>

          <Divider sx={{ mb: 4, borderColor: C.border }} />

          <Section title="8. Intellectual property">
            <P>
              All Nui content — including design, logos, text, source code, graphics, interface, and analysis
              methodology — is the exclusive property of its owners and is protected by applicable
              intellectual property law.
            </P>
            <P>
              You're granted a limited, personal, non-exclusive, non-transferable license to use the Service
              as contemplated by these Terms. This license doesn't transfer any intellectual property rights to you.
            </P>
            <P>
              If you believe content on Nui infringes a copyright you own, email{" "}
              <strong>info@nuiapp.com</strong> with a description of the work, the material you believe
              infringes it, and your contact information. We'll review and respond to valid complaints.
            </P>
          </Section>

          <Divider sx={{ mb: 4, borderColor: C.border }} />

          <Section title="9. Indemnification">
            <P>
              To the fullest extent permitted by applicable law, you agree to indemnify and hold Nui, its
              team, and its service providers harmless from claims, losses, and expenses (including
              reasonable attorneys' fees) arising from your violation of these Terms, your misuse of the
              Service, or your violation of any law or third-party right — except to the extent we caused
              the loss.
            </P>
          </Section>

          <Divider sx={{ mb: 4, borderColor: C.border }} />

          <Section title="10. Disclaimer of warranties">
            <P>
              The Service is provided "as is" and "as available," without warranties of any kind, express
              or implied, including warranties of merchantability, fitness for a particular purpose, or
              non-infringement. We don't guarantee the Service will be uninterrupted, error-free, or free of
              harmful components, or that AI-generated results will be accurate or complete.
            </P>
          </Section>

          <Divider sx={{ mb: 4, borderColor: C.border }} />

          <Section title="11. Limitation of liability">
            <P>
              To the maximum extent permitted by applicable law, Nui is not liable for direct, indirect,
              incidental, or consequential damages arising from use or inability to use the Service, including:
            </P>
            <Box component="ul" sx={{ pl: 1, mb: 2 }}>
              <Li>Decisions you make based on AI-generated analysis, recipes, or training plans.</Li>
              <Li>Physical injury or health effects related to activities you perform based on Service content.</Li>
              <Li>Temporary service interruptions due to maintenance or causes outside our control.</Li>
              <Li>Inaccuracies in AI-generated results.</Li>
            </Box>
            <P>
              Nothing in this section limits liability that can't be limited under applicable law, or
              affects mandatory consumer-protection rights available to you where you live.
            </P>
          </Section>

          <Divider sx={{ mb: 4, borderColor: C.border }} />

          <Section title="12. Changes to the service">
            <P>
              We may modify, suspend, or discontinue the Service, or any part of it, at any time. For material
              changes that affect your existing rights, we'll give you at least 15 days' notice by email.
            </P>
          </Section>

          <Divider sx={{ mb: 4, borderColor: C.border }} />

          <Section title="13. Governing law and disputes">
            <P>
              Nui is operated by a team based in Argentina. These Terms are governed by the laws of Argentina,
              without regard to conflict-of-law principles, except where a mandatory local consumer-protection
              law gives you rights that can't be waived by agreement — those rights remain fully available to you.
            </P>
            <P>
              We'll try to resolve any dispute informally first — email us at <strong>info@nuiapp.com</strong>{" "}
              and we'll do our best to sort it out directly before either of us pursues a formal claim.
            </P>
          </Section>

          <Divider sx={{ mb: 4, borderColor: C.border }} />

          <Section title="14. Electronic communications">
            <P>
              By using the Service, you agree to receive certain electronic communications from us (e.g.
              account, billing, and service notices) at the email address you provide. You can manage
              non-essential notifications from your profile settings.
            </P>
          </Section>

          <Divider sx={{ mb: 4, borderColor: C.border }} />

          <Section title="15. Miscellaneous">
            <P>
              <strong>Assignment:</strong> we may assign our rights and obligations under these Terms; you
              may not, without our written consent. <strong>Waiver:</strong> our failure to enforce any part
              of these Terms isn't a waiver of our right to do so later. <strong>Severability:</strong> if
              any provision of these Terms is found unenforceable, the rest remains in effect.
            </P>
          </Section>

          <Divider sx={{ mb: 4, borderColor: C.border }} />

          <Section title="16. Contact">
            <P>
              Questions about these Terms? Reach us at:<br />
              📧 <strong>info@nuiapp.com</strong>
            </P>
          </Section>

          <Box sx={{ mt: 4, p: 3, borderRadius: 3, bgcolor: "#FFF8E1", border: "1px solid rgba(245,166,35,0.25)" }}>
            <Typography sx={{ fontSize: 13, color: "#7B5800", fontWeight: 700, mb: 0.5 }}>
              ⚕️ Important health notice
            </Typography>
            <Typography sx={{ fontSize: 13, color: "#5D4200", lineHeight: 1.7 }}>
              Nui is a nutrition-information and wellness tool, not a medical service. Analyses, scores,
              and plans generated by AI are informational. If you have any concern about your health, diet,
              or physical condition, always consult a licensed health professional.
            </Typography>
          </Box>

        </Paper>
      </Container>
    </Box>
  );
}
